# Generated by Django 3.0.5 on 2020-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200504_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_item',
            field=models.BooleanField(default=False),
        ),
    ]
